version: 2.

jobs:
   # Job pour construire le backend Symfony
  build_backend:
    docker:
      - image: circleci/php:8.1-cli-buster-node
    steps:
      - checkout
      - run:
          name: Installer les dépendances Composer
          command: composer install
          working_directory: ./backend
      - run:
          name: Build du backend Symfony
          command: |
            php bin/console cache:clear
            php bin/console doctrine:migrations:migrate --no-interaction
          working_directory: ./backend

  # Job pour construire le frontend Next.js
  build_frontend:
    docker:
      - image: circleci/node:18
    steps:
      - checkout
      - run:
          name: Installer les dépendances Node.js
          command: npm install
          working_directory: ./frontend
      - run:
          name: Build du frontend Next.js
          command: npm run build
          working_directory: ./frontend
  test_backend:
    docker:
      - image: cimg/php:8.1-node  # Utiliser une image PHP avec Node
    steps:
      - checkout
      - run:
          name: Vérifier le contenu du dépôt
          command: ls -l 
      - run:
          name: Vérifier le contenu du dossier 
          command: ls -l backend  # Vérifie que le répertoire backend est bien là
      - run:
          name: Installer les dépendances Composer
          command: |
            composer install
      - run:
          name: Exécuter les tests PHPUnit
          command: |
            php vendor/bin/phpunit --debug
  # Job pour tester le frontend Next.js
  test_frontend:
    docker:
      - image: cimg/node:20.17.0
    steps:
      - checkout

      - run:
          name: Vérifier le contenu du frontend
          command: ls -l frontend  # Vérifie que le répertoire frontend est bien là
      - run:
          name: Installer les dépendances npm
          command: |
            npm install
      - run:
          name: Exécuter les tests Frontend
          command: |
            npm run test



workflows:
    version: 2
    pipeline:
      jobs:
        - test_backend
        - test_frontend
        - build_backend:
            requires:
              - test_backend
        - build_frontend:
            requires:
              - test_frontend
        # - deploy:
        #     requires:
        #       - build_backend
        #       - build_frontend
